### ISSUE TITLE
nit pick on css formatting

### ISSUE THREAD

**Issue by wils0651** [BoiseStateCS401/CS401-activity-teamawesome#1]
Very well done web page. Since I couldn't really find anything wrong, this is my only suggestion. I've always seen css formatting done so that the selector is on the same line as the open curly brace, like this:
p {
  thing1: stuff;
}

rather than (as done here):
p
{
  thing1: stuff;
}

Obviously, the file still works fine, but this might be the suggested convention.

**Comment by jjcbsu** [comment]
Good spotting!  Yes, the css codecademy automatically makes 
p{
}
instead of 
p
{
}
which might very well be the usual css convention.  However since we don't have a "company style sheet" that we need to follow we chose to use the second style as that is what we are more comfortable with.
